version: 2.1

orbs:
  docker: circleci/docker@1.2.1

jobs:
  test:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: michaelmok/cimg-puppeteer
      - run:
          name: Test built Docker image
          command: |
            docker run \
              --name pptr_image_test \
              --mount type=bind,source="$(pwd)"/test,target=/home/circleci/project \
              $DOCKER_LOGIN/cimg-puppeteer:$CIRCLE_SHA1 \
              bash ./test.sh

workflows:
  test:
    jobs:
      - test:
          context: DOCKER_CREDENTIALS
