version: 2.1

orbs:
  docker: circleci/docker@1.2.1

executors:
  machine:
    parameters:
      image:
        default: ubuntu-1604:202007-01
        type: string
    machine:
      image: << parameters.image >>

jobs:
  test:
    executor: machine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            make build \
              name=$CIRCLE_PROJECT_REPONAME \
              versions=current \
              tag=$CIRCLE_SHA1
      - run:
          name: Test built Docker image
          command: |
            docker run \
              --detach \
              --init \
              --privileged \
              --tty \
              --name $CONTAINER \
              --user circleci:circleci \
              $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
              bash
            docker cp ./fixtures/. $CONTAINER:/home/circleci/project/fixtures
            docker cp ./Makefile $CONTAINER:/home/circleci/project/Makefile
            docker exec $CONTAINER make test
            docker kill $CONTAINER
            docker rm $CONTAINER_NAME
          environment:
            CONTAINER: cimg-puppeteer

  get-tags:
    docker:
      - image: cimg/base:2020.07
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Get all available tags for cimg/node
          command: make get-tags name="cimg/node" output="./workspace/tags.txt"
      - persist_to_workspace:
          root: ./workspace
          paths:
            - tags.txt

  build-and-publish:
    executor: machine
    parallelism: 4
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - docker/check:
          use-docker-credentials-store: true
      - run:
          name: Build Docker image
          command: |
            cat ./workspace/tags.txt | circleci tests split > ./workspace/build-tags.txt
            make build name="$DOCKER_LOGIN/puppeteer" versions="$(cat ./workspace/build-tags.txt)"

workflows:
  version: 2

  test:
    jobs:
      - test:
          context: DOCKER_CREDENTIALS

  release:
    jobs:
      - get-tags
      - build-and-publish:
          context: DOCKER_CREDENTIALS
          requires:
            - get-tags
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - main
