version: 2.1

commands:
  build-images:
    parameters:
      include-non-minor-tags:
        default: true
        type: boolean
    steps:
      - attach_workspace:
          at: ./workspace
      - unless:
          condition: << parameters.include-non-minor-tags >>
          steps:
            - run:
                name: Filter non-semver-minor tags
                command: make filter-non-minor-tags input="./workspace/tags.txt"
      - run:
          name: Split and set Docker tags to build
          command: echo 'export VERSIONS="$(circleci tests split <./workspace/tags.txt | tr "\n" " ")"' >> $BASH_ENV
      - run:
          name: Build Docker images
          command: |
            make -j "${CONCURRENCY:=1}" -O build \
              name="${DOCKER_LOGIN}/puppeteer" \
              progress="plain" \
              versions="${VERSIONS}"

  set-concurrency:
    steps:
      - run:
          name: Set max possible concurrency for current executor
          command: echo 'export CONCURRENCY="$(grep -cP '^processor' /proc/cpuinfo)"' >> $BASH_ENV

orbs:
  docker: circleci/docker@1.2.1

executors:
  machine:
    parameters:
      image:
        default: ubuntu-1604:202007-01
        type: string
    machine:
      image: << parameters.image >>

jobs:
  get-tags:
    docker:
      - image: cimg/base:2020.07
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Get all available tags for cimg/node
          command: make get-tags name="cimg/node" output="./workspace/tags.txt"
      - persist_to_workspace:
          root: ./workspace
          paths:
            - tags.txt

  test:
    executor: machine
    parallelism: 4
    working_directory: ~/project
    steps:
      - checkout
      - set-concurrency
      - build-images:
          include-non-minor-tags: false
      - run:
          name: Test built Docker images
          command: make -j "${CONCURRENCY}" -O test name="${DOCKER_LOGIN}/puppeteer" versions="${VERSIONS}"

  publish:
    executor: machine
    parallelism: 4
    working_directory: ~/project
    steps:
      - checkout
      - docker/check:
          use-docker-credentials-store: true
      - set-concurrency
      - build-images
      - run:
          name: Publish built Docker images
          command: make -j "${CONCURRENCY}" -O publish name="${DOCKER_LOGIN}/puppeteer" versions="${VERSIONS}"

workflows:
  version: 2

  test:
    jobs:
      - get-tags
      - test:
          context: DOCKER_CREDENTIALS
          requires:
            - get-tags

#  release:
#    jobs:
#      - get-tags
#      - publish:
#          context: DOCKER_CREDENTIALS
#          requires:
#            - get-tags
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - main
