version: 2.1

orbs:
  docker: circleci/docker@1.2.1

jobs:
  test:
    executor: docker/machine
    working_directory: ~/project
    steps:
      - checkout
      - docker/check:
          use-docker-credentials-store: true
      - docker/build:
          image: cimg-puppeteer
      - run:
          name: Test built Docker image
          command: |
            CONTAINER=cimg-puppeteer
            WORKING_DIR=/home/circleci/project

            docker run \
              --detach \
              --init \
              --privileged \
              --tty \
              --name $CONTAINER \
              --user circleci:circleci \
              cimg-puppeteer:$CIRCLE_SHA1 \
              bash
            docker cp ./test/. $CONTAINER:$WORKING_DIR
            docker exec $CONTAINER pwd
            docker exec $CONTAINER sudo chown -R $USER: .
            docker exec $CONTAINER sudo chmod +x ./test.sh
            docker exec $CONTAINER ./test.sh
            docker kill $CONTAINER
            docker rm $CONTAINER

workflows:
  test:
    jobs:
      - test:
          context: DOCKER_CREDENTIALS
