version: 2.1

orbs:
  docker: circleci/docker@1.2.1

jobs:
  test:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: pmmmwh/cimg-puppeteer
      - run:
          command: |
            WORKING_DIR="$(cd "$(dirname "$CIRCLE_WORKING_DIRECTORY")"; pwd)/$(basename "$CIRCLE_WORKING_DIRECTORY")"

            docker run \
              --name pptr_image_test \
              --mount type=bind,source="$(pwd)"/test,target=$WORKING_DIR \
              pmmmwh/puppeteer:$CIRCLE_SHA1 \
              bash ./test.sh

workflows:
  test:
    jobs:
      - test:
          context: DOCKER_CREDENTIALS
